spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
jwt:
  secret: secreto